<?php

namespace Modules\Item\Entities;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Item extends Model
{
    use HasFactory, Sluggable;

    protected $guarded = ['id'];

    protected static function newFactory()
    {
        return \Modules\Item\Database\factories\ItemFactory::new();
    }

    public function getRouteKeyName()
    {
        return 'item_slug'; // TODO: Change the autogenerated stub
    }

    public function sluggable(): array
    {
        return [
            'item_slug' => ['source' => 'item_name']
        ];
    }
}
